### ISSUE TITLE
[BUG]: Custom external browser setting does not work - again

### ISSUE THREAD

**Issue by richardstevenhack** [martinrotter/rssguard#1411]
### Brief description of the issue

Running the latest RSSGuard Flatpak 4.7.0 on latest openSUSE Tumbleweed. Previously, after fixing the issue back in February with the fix suggested by Guilherme Silva, I was able to open Firefox to process RSS feed items with Firefox as the external browser.

Today after an openSUSE Tumbleweed update and a Flatpak update, I can no longer do so. 

Also, in addition, not only am I not able to open with external browser, right clicking only allows two actions: Open in external tool, and Labels, both of which are greyed out. All other options of right-click are also greyed out.

### How to reproduce the bug?

1) Select a feed article.
2) Right-click the feed article.

### What was the expected result?

The right-click should show the option "open in external browser" as available, among other options.

### What actually happened?

The only right-click options which appear active are "Open with external tool" and "Labels". All other options in the list are greyed out and the options for the two active options are also greyed out.

Please NOTE: Pursuant to having had the problem in February, I added the following based on instructions from Guilherme Silva:
1. Break the sandbox:
flatpak --user override --talk-name=org.freedesktop.Flatpak io.github.martinrotter.rssguard
2. Restart RSS Guard
3. Set your "web browser executable" to:
/usr/bin/flatpak-spawn
4. Use this as your parameters (replacing firefox by your browser of choice):
--host firefox "%1"

All those are still the configuration I am using with the current problem.

One thing I did discover is that after the openSUSE Tumbleweed update, flatpak-spawn was no longer in /usr/bin or anywhere in the system. I had to reinstall it from the openSUSE repository. I don't know why that happened. I assumed that was part of the flatpak system and that it would be kept updated by the flatpak system.

### Debug log

time="     0.102" type="debug" -> core: Initializing settings in '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.102" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.102" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.102" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.246" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.246" type="debug" -> database: File-based SQLite database has version '8'.
time="     0.246" type="debug" -> gui: Available icon theme paths: QList(/app/share/icons, /usr/share/icons, /usr/share/runtime/share/icons, /run/host/user-share/icons, /run/host/share/icons, :/icons, :/graphics, /home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/icons, /app/bin/icons)
time="     0.247" type="debug" -> gui: Installed icon themes are: '', 'Breeze_Light', 'breeze', 'breeze-dark', 'breeze_cursors', 'hicolor', 'Adwaita', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.247" type="debug" -> gui: Loading icon theme 'Breeze'.
time="     0.247" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     0.247" type="debug" -> gui: Base file ':/skins/nudus-base/html_wrapper.html' exists, using it for the skin.
time="     0.247" type="debug" -> gui: Local file ':/skins/nudus-light/html_style.css' exists, using it for the skin.
time="     0.247" type="debug" -> gui: Base file ':/skins/nudus-base/html_enclosure_image.html' exists, using it for the skin.
time="     0.247" type="debug" -> gui: Base file ':/skins/nudus-base/html_single_message.html' exists, using it for the skin.
time="     0.247" type="debug" -> gui: Base file ':/skins/nudus-base/html_enclosure_every.html' exists, using it for the skin.
time="     0.247" type="debug" -> gui: Local file ':/skins/nudus-light/qt_style.qss' exists, using it for the skin.
time="     0.247" type="debug" -> gui: Base file ':/skins/nudus-base/html_adblocked.html' exists, using it for the skin.
time="     0.247" type="debug" -> gui: OS defines color scheme: 'Qt::ColorScheme::Light'.
time="     0.247" type="debug" -> gui: Setting style: ''.
time="     0.248" type="debug" -> gui: Skin 'nudus-light' loaded. Lite: 'false'.
time="     0.248" type="warning" -> core: User CSS style was not provided in file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/web/user-styles.css'.
time="     0.248" type="debug" -> network: Persistent web data storage path: '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/web/storage'.
time="     0.248" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.248" type="debug" -> core: SQLite version: '3.42.0'.
time="     0.251" type="debug" -> core: OpenSSL version: 'OpenSSL 3.1.5 30 Jan 2024'.
time="     0.251" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.251" type="debug" -> core: Global thread pool has 32 threads.
time="     0.251" type="debug" -> core: Setting locale for LC_NUMERIC to C as libmpv requires it.
time="     0.251" type="debug" -> core: Instantiated class  'Application'.
time="     0.252" type="debug" -> database: SQLite database connection 'MessagesModel' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.253" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.253" type="debug" -> core: Auto-download timer started with interval 10000 ms.
time="     0.253" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.316" type="debug" -> gui: Creating main application form in thread: '0x7faf0dba6000'.
time="     0.321" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.321" type="debug" -> gui: Article list header geometries changed.
time="     0.324" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.335" type="debug" -> gui: Article list header geometries changed.
time="     0.337" type="debug" -> gui: Article list header geometries changed.
time="     0.339" type="debug" -> gui: Article list header geometries changed.
time="     0.342" type="debug" -> gui: Article list header geometries changed.
time="     0.352" type="debug" -> gui: Creating tray icon menu.
time="     0.363" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.363" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.363" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.date_created ASC, Messages.is_read ASC;'.
time="     0.365" type="debug" -> core: Showing the main window when the application is starting.
time="     0.369" type="debug" -> gui: Article list header geometries changed.
time="     0.369" type="debug" -> gui: Article list header geometries changed.
time="     0.370" type="debug" -> gui: Article list header geometries changed.
time="     0.371" type="debug" -> database: SQLite database connection 'FeedReader' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.372" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-feedly.so' loaded.
time="     0.374" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-gmail.so' loaded.
time="     0.375" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-greader.so' loaded.
time="     0.376" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-nextcloud.so' loaded.
time="     0.379" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-standard.so' loaded.
time="     0.380" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-ttrss.so' loaded.
time="     0.380" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.380" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.380" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.380" type="debug" -> database: SQLite database connection 'NextcloudServiceEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.380" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.381" type="debug" -> core: Destructing 'std-rss' plugin.
time="     0.381" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.381" type="debug" -> core: Custom ID of feed when loading from DB is '10'.
time="     0.381" type="debug" -> core: Custom ID of feed when loading from DB is '11'.
time="     0.381" type="debug" -> core: Custom ID of feed when loading from DB is '12'.
time="     0.381" type="debug" -> core: Custom ID of feed when loading from DB is '13'.
time="     0.381" type="debug" -> core: Custom ID of feed when loading from DB is '14'.
time="     0.381" type="debug" -> core: Custom ID of feed when loading from DB is '15'.
time="     0.381" type="debug" -> core: Custom ID of feed when loading from DB is '16'.
time="     0.381" type="debug" -> core: Custom ID of feed when loading from DB is '17'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '18'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is 'new'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '20'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '21'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '22'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '23'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '24'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '25'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '26'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '27'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '28'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '29'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '30'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '31'.
time="     0.382" type="debug" -> core: Custom ID of feed when loading from DB is '32'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '33'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '34'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '35'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '36'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '37'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '38'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '39'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '40'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '41'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '42'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '43'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '44'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '45'.
time="     0.383" type="debug" -> core: Custom ID of feed when loading from DB is '46'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '47'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '58'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '59'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '60'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '61'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '62'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '63'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '64'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '65'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '66'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '67'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '68'.
time="     0.384" type="debug" -> core: Custom ID of feed when loading from DB is '69'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '70'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '71'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '72'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '73'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '74'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '75'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '76'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '77'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '78'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '79'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '80'.
time="     0.385" type="debug" -> core: Custom ID of feed when loading from DB is '81'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '82'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '83'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '84'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '85'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '86'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '87'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '88'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '89'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '90'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '91'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '92'.
time="     0.386" type="debug" -> core: Custom ID of feed when loading from DB is '93'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '94'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '95'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '96'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '97'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '99'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '100'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '101'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '102'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '103'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '104'.
time="     0.387" type="debug" -> core: Custom ID of feed when loading from DB is '105'.
time="     0.387" type="warning" -> core: Feed 'new' is loose, skipping it.
time="     0.387" type="debug" -> database: SQLite database connection 'RecycleBin' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.388" type="debug" -> database: SQLite database connection 'ImportantNode' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.388" type="debug" -> database: SQLite database connection 'UnreadNode' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.388" type="debug" -> database: SQLite database connection 'LabelsNode' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.388" type="debug" -> database: SQLite connection 'StandardServiceRoot' is already active.
time="     0.388" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.388" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.388" type="debug" -> gui: User wants to have tray icon.
time="     0.388" type="warning" -> gui: Showing tray icon with little delay.
time="     0.388" type="debug" -> gui: Feed list item expanded - rhack (RSS/ATOM/JSON)
time="     0.388" type="debug" -> gui: Feed list item expanded - Original Feeds
time="     0.388" type="debug" -> gui: Feed list item expanded - Imported Feeds
time="     0.388" type="debug" -> core: No execution message received from other app instances.
time="     0.432" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     3.535" type="warning" -> gui: Tray icon is available, showing now.
time="     3.538" type="debug" -> gui: Creating SystemTrayIcon instance.
time="     3.538" type="debug" -> gui: Showing tray icon immediately.
time="     3.544" type="debug" -> gui: Tray icon displayed.
time="     4.591" type="debug" -> gui: Main window hide event
time="     4.591" type="debug" -> gui: Article list header geometries changed.
time="     4.592" type="debug" -> gui: Main window close event
time="    45.537" type="debug" -> core: Saved data with auto-saver for 'CookieJar' and method 'saveCookies'.
time="   167.143" type="debug" -> core: Cleaning up resources and saving application state.
time="   167.143" type="debug" -> core: Close lock was obtained safely.
time="   167.143" type="debug" -> core: Stopping StandardServiceRoot instance.time="   167.143" type="debug" -> feed-downloader: Destroying FeedDownloader instance.

time="   167.145" type="debug" -> gui: Destroying FormMain instance.
time="   167.146" type="debug" -> gui: Destroying TabWidget instance.
time="   167.146" type="debug" -> gui: Destroying FeedMessageViewer instance.
time="   167.146" type="debug" -> gui: Destroying BaseToolBar instance.
time="   167.148" type="debug" -> network: Destroying Downloader instance.
time="   167.148" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   167.150" type="debug" -> gui: Destroying MessagesView instance.
time="   167.151" type="debug" -> gui: Destroying BaseToolBar instance.
time="   167.151" type="debug" -> gui: Destroying FeedsView instance.
time="   167.151" type="debug" -> gui: Destroying TabBar instance.
time="   167.152" type="debug" -> gui: Destroying StatusBar instance.
time="   167.152" type="debug" -> gui: Destroying SystemTrayIcon instance.
time="   167.169" type="debug" -> core: Destroying Application instance.
time="   167.169" type="debug" -> core: Destroying Mutex instance.
time="   167.174" type="debug" -> gui: Destroying IconFactory instance.
time="   167.174" type="debug" -> core: Destroying FeedReader instance.
time="   167.174" type="debug" -> core: Service 'feedly' will be deleted by runtime.
time="   167.174" type="debug" -> core: Service 'gmail' will be deleted by runtime.
time="   167.174" type="debug" -> core: Service 'greader' will be deleted by runtime.
time="   167.175" type="debug" -> core: Service 'nextcloud' will be deleted by runtime.
time="   167.175" type="debug" -> core: Service 'std-rss' will be deleted by runtime.
time="   167.175" type="debug" -> core: Service 'tt-rss' will be deleted by runtime.
time="   167.175" type="debug" -> feed-model: Destroying FeedsModel instance.
time="   167.175" type="debug" -> feed-model: Destroying FeedsProxyModel instance
time="   167.175" type="debug" -> message-model: Destroying MessagesModel instance.
time="   167.175" type="debug" -> message-model: Destroying MessagesProxyModel instance.
core: Destructing 'feedly' plugin.
gmail: Destructing 'gmail' plugin.
core: Destructing 'greader' plugin.
gmail: Destructing 'nextcloud' plugin.
core: Destructing 'std-rss' plugin.
gmail: Destructing 'tt-rss' plugin.
time="     0.090" type="debug" -> core: Initializing settings in '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.090" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.
time="     0.090" type="debug" -> core: Application localization 'en_US' loaded successfully, specifically sublocalization 'en_US' was loaded.
time="     0.090" type="warning" -> core: Qt localization 'en_US' WAS NOT loaded successfully.
time="     0.249" type="debug" -> database: File-based SQLite database connection 'DatabaseFactory' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.249" type="debug" -> database: File-based SQLite database has version '8'.
time="     0.249" type="debug" -> gui: Available icon theme paths: QList(/app/share/icons, /usr/share/icons, /usr/share/runtime/share/icons, /run/host/user-share/icons, /run/host/share/icons, :/icons, :/graphics, /home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/icons, /app/bin/icons)
time="     0.250" type="debug" -> gui: Installed icon themes are: '', 'Breeze_Light', 'breeze', 'breeze-dark', 'breeze_cursors', 'hicolor', 'Adwaita', 'Breeze', 'Breeze Dark', 'Faenza', 'Numix'
time="     0.250" type="debug" -> gui: Loading icon theme 'Breeze'.
time="     0.250" type="debug" -> gui: Found path of base skin: ':/skins/nudus-base'.
time="     0.250" type="debug" -> gui: Base file ':/skins/nudus-base/html_wrapper.html' exists, using it for the skin.
time="     0.250" type="debug" -> gui: Local file ':/skins/nudus-light/html_style.css' exists, using it for the skin.
time="     0.250" type="debug" -> gui: Base file ':/skins/nudus-base/html_enclosure_image.html' exists, using it for the skin.
time="     0.250" type="debug" -> gui: Base file ':/skins/nudus-base/html_single_message.html' exists, using it for the skin.
time="     0.250" type="debug" -> gui: Base file ':/skins/nudus-base/html_enclosure_every.html' exists, using it for the skin.
time="     0.250" type="debug" -> gui: Local file ':/skins/nudus-light/qt_style.qss' exists, using it for the skin.
time="     0.250" type="debug" -> gui: Base file ':/skins/nudus-base/html_adblocked.html' exists, using it for the skin.
time="     0.250" type="debug" -> gui: OS defines color scheme: 'Qt::ColorScheme::Light'.
time="     0.250" type="debug" -> gui: Setting style: ''.
time="     0.251" type="debug" -> gui: Skin 'nudus-light' loaded. Lite: 'false'.
time="     0.252" type="warning" -> core: User CSS style was not provided in file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/web/user-styles.css'.
time="     0.252" type="debug" -> network: Persistent web data storage path: '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/web/storage'.
time="     0.252" type="debug" -> network: Disabling application-wide proxy completely.
time="     0.252" type="debug" -> core: SQLite version: '3.42.0'.
time="     0.255" type="debug" -> core: OpenSSL version: 'OpenSSL 3.1.5 30 Jan 2024'.
time="     0.255" type="debug" -> core: OpenSSL supported: 'true'.
time="     0.255" type="debug" -> core: Global thread pool has 32 threads.
time="     0.255" type="debug" -> core: Setting locale for LC_NUMERIC to C as libmpv requires it.
time="     0.255" type="debug" -> core: Instantiated class  'Application'.
time="     0.257" type="debug" -> database: SQLite database connection 'MessagesModel' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.258" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1;'.
time="     0.258" type="debug" -> core: Auto-download timer started with interval 10000 ms.
time="     0.258" type="debug" -> core: Creating FeedDownloader singleton.
time="     0.294" type="debug" -> gui: Creating main application form in thread: '0x7fde4dc15000'.
time="     0.297" type="debug" -> gui: Current row changed - proxy 'QModelIndex(-1,-1,0x0,QObject(0x0))', source 'QModelIndex(-1,-1,0x0,QObject(0x0))'.
time="     0.297" type="debug" -> gui: Article list header geometries changed.
time="     0.301" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="     0.311" type="debug" -> gui: Article list header geometries changed.
time="     0.313" type="debug" -> gui: Article list header geometries changed.
time="     0.316" type="debug" -> gui: Article list header geometries changed.
time="     0.318" type="debug" -> gui: Article list header geometries changed.
time="     0.328" type="debug" -> gui: Creating tray icon menu.
time="     0.339" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.339" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     0.340" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.date_created ASC, Messages.is_read ASC;'.
time="     0.341" type="debug" -> core: Showing the main window when the application is starting.
time="     0.346" type="debug" -> gui: Article list header geometries changed.
time="     0.346" type="debug" -> gui: Article list header geometries changed.
time="     0.346" type="debug" -> gui: Article list header geometries changed.
time="     0.347" type="debug" -> database: SQLite database connection 'FeedReader' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.349" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-feedly.so' loaded.
time="     0.351" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-gmail.so' loaded.
time="     0.352" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-greader.so' loaded.
time="     0.353" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-nextcloud.so' loaded.
time="     0.355" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-standard.so' loaded.
time="     0.357" type="debug" -> core: Plugin '/app/lib/rssguard/librssguard-ttrss.so' loaded.
time="     0.357" type="debug" -> database: SQLite database connection 'FeedlyEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.357" type="debug" -> database: SQLite database connection 'GmailEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.357" type="debug" -> database: SQLite database connection 'GreaderEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.357" type="debug" -> database: SQLite database connection 'NextcloudServiceEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.357" type="debug" -> database: SQLite database connection 'StandardServiceEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.358" type="debug" -> core: Destructing 'std-rss' plugin.
time="     0.358" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.358" type="debug" -> core: Custom ID of feed when loading from DB is '10'.
time="     0.358" type="debug" -> core: Custom ID of feed when loading from DB is '11'.
time="     0.358" type="debug" -> core: Custom ID of feed when loading from DB is '12'.
time="     0.358" type="debug" -> core: Custom ID of feed when loading from DB is '13'.
time="     0.358" type="debug" -> core: Custom ID of feed when loading from DB is '14'.
time="     0.358" type="debug" -> core: Custom ID of feed when loading from DB is '15'.
time="     0.358" type="debug" -> core: Custom ID of feed when loading from DB is '16'.
time="     0.358" type="debug" -> core: Custom ID of feed when loading from DB is '17'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '18'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is 'new'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '20'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '21'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '22'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '23'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '24'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '25'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '26'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '27'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '28'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '29'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '30'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '31'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '32'.
time="     0.359" type="debug" -> core: Custom ID of feed when loading from DB is '33'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '34'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '35'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '36'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '37'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '38'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '39'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '40'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '41'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '42'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '43'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '44'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '45'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '46'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '47'.
time="     0.360" type="debug" -> core: Custom ID of feed when loading from DB is '58'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '59'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '60'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '61'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '62'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '63'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '64'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '65'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '66'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '67'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '68'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '69'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '70'.
time="     0.361" type="debug" -> core: Custom ID of feed when loading from DB is '71'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '72'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '73'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '74'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '75'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '76'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '77'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '78'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '79'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '80'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '81'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '82'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '83'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '84'.
time="     0.362" type="debug" -> core: Custom ID of feed when loading from DB is '85'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '86'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '87'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '88'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '89'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '90'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '91'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '92'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '93'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '94'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '95'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '96'.
time="     0.363" type="debug" -> core: Custom ID of feed when loading from DB is '97'.
time="     0.364" type="debug" -> core: Custom ID of feed when loading from DB is '99'.
time="     0.364" type="debug" -> core: Custom ID of feed when loading from DB is '100'.
time="     0.364" type="debug" -> core: Custom ID of feed when loading from DB is '101'.
time="     0.364" type="debug" -> core: Custom ID of feed when loading from DB is '102'.
time="     0.364" type="debug" -> core: Custom ID of feed when loading from DB is '103'.
time="     0.364" type="debug" -> core: Custom ID of feed when loading from DB is '104'.
time="     0.364" type="debug" -> core: Custom ID of feed when loading from DB is '105'.
time="     0.364" type="warning" -> core: Feed 'new' is loose, skipping it.
time="     0.364" type="debug" -> database: SQLite database connection 'RecycleBin' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.364" type="debug" -> database: SQLite database connection 'ImportantNode' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.364" type="debug" -> database: SQLite database connection 'UnreadNode' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.364" type="debug" -> database: SQLite database connection 'LabelsNode' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.365" type="debug" -> database: SQLite connection 'StandardServiceRoot' is already active.
time="     0.365" type="debug" -> database: SQLite database connection 'StandardServiceRoot' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.365" type="debug" -> database: SQLite database connection 'TtRssServiceEntryPoint' to file '/home/rhack/.var/app/io.github.martinrotter.rssguard/config/RSS Guard 4/database/database.db' seems to be established.
time="     0.365" type="debug" -> gui: User wants to have tray icon.
time="     0.365" type="warning" -> gui: Showing tray icon with little delay.
time="     0.365" type="debug" -> gui: Feed list item expanded - rhack (RSS/ATOM/JSON)
time="     0.365" type="debug" -> gui: Feed list item expanded - Original Feeds
time="     0.365" type="debug" -> gui: Feed list item expanded - Imported Feeds
time="     0.365" type="debug" -> core: No execution message received from other app instances.
time="     0.410" type="debug" -> gui: Hovered link: 'QUrl()'.
time="     3.393" type="warning" -> gui: Tray icon is available, showing now.
time="     3.394" type="debug" -> gui: Creating SystemTrayIcon instance.
time="     3.394" type="debug" -> gui: Showing tray icon immediately.
time="     3.398" type="debug" -> gui: Tray icon displayed.
time="     4.430" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="     4.430" type="debug" -> core: Displaying messages from feeds IDs: ''14', '15', '16', '17', '18', '20', '21', '22', '23', '24'' and URLs: 'https://lwn.net/headlines/newrss, https://www.tecmint.com/feed/, http://lxer.com/module/newswire/headlines.rss, https://itsfoss.com/feed/, http://www.linux.com/index.rss, http://www.howtoforge.com/node/feed, https://linuxways.net/feed/, https://ostechnix.com/feed/, http://distrowatch.com/news/dw.xml, https://linuxinsider.com/rss-feed'.
time="     4.431" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE Feeds.custom_id IN ('14', '15', '16', '17', '18', '20', '21', '22', '23', '24') AND Messages.is_deleted = 0 AND Messages.is_pdeleted = 0 AND Messages.account_id = 1 ORDER BY Messages.date_created ASC, Messages.is_read ASC;'.
time="     7.788" type="debug" -> gui: Message list got focus with reason 'Qt::MouseFocusReason'.
time="     7.788" type="debug" -> gui: Current row changed - proxy 'QModelIndex(3,6,0x56322a95fb10,MessagesProxyModel(0x56322a72e2a0, name = MessagesProxyModel))', source 'QModelIndex(3,6,0x0,MessagesModel(0x56322a74a8d0))'.
time="     9.746" type="debug" -> gui: Message list got focus with reason 'Qt::PopupFocusReason'.

### Operating system and version

* OS: openSUSE Tumbleweed 20240515 Flatpak Version:  Flatpak 1.15.8
* RSS Guard version:  
* ### RSS Guard
**Version:** 4.7.0 (built on Linux/x86_64)
**Revision:** 
**Build date:** 5/16/24 1:32 AM
**OS:** KDE Flatpak runtime
**Qt:** 6.6.3 (compiled against 6.6.3)

**Comment by guihkx** [comment]
I'll try to reproduce this issue soon, and I'll get back to you.

In the meantime, I have a note on this comment:

>One thing I did discover is that after the openSUSE Tumbleweed update, flatpak-spawn was no longer in /usr/bin or anywhere in the system. I had to reinstall it from the openSUSE repository. I don't know why that happened. I assumed that was part of the flatpak system and that it would be kept updated by the flatpak system.

You won't find `flatpak-spawn` on your system's `/usr/bin`.

That executable is only available inside the Flatpak runtime RSS Guard uses (i.e. KDE):

```
$ flatpak run --command=which io.github.martinrotter.rssguard flatpak-spawn
/usr/bin/flatpak-spawn
```

That means you don't have to install anything on your system to make `flatpak-spawn` available, because it's already included with RSS Guard's flatpak runtime.

**Comment by guihkx** [comment]
Just tested it. The issue is not reproducible for me with RSS Guard 4.7.0.

Can you please provide some extra information so we can understand why this is not working for you?

* Post the output of this command:
  ```
  cat ~/.local/share/flatpak/overrides/io.github.martinrotter.rssguard
  ```

* Post a screenshot of your External web browser settings in RSS Guard, i.e.:

  ![image](https://github.com/martinrotter/rssguard/assets/626206/b0c321e5-3857-42c1-b089-89f30af74208)

* Finally, post the output of these two commands:

  ```
  which firefox
  firefox --version
  ```

**Comment by martinrotter** [comment]
@guihkx So this is actually not related to rssguard as it seems.

@guihkx By the way, huge thanks for your contribution to RSS Guard community. You are MVP when it comes to RSS Guard's Flatpak port and other stuff. Thanks once more.

**Comment by guihkx** [comment]
Thanks for the kind words. And it's no problem, I'm glad to help whenever I'm able to. :)

>@guihkx So this is actually not related to rssguard as it seems.

Yeah, I suspect it's a configuration issue, unrelated to RSS Guard itself.

But I'd like to wait for OP's response, just to be sure...

**Comment by martinrotter** [comment]
Sure will keep this opened, not a problem.

**Comment by richardstevenhack** [comment]
Here is the output of the commands:
rhack@localhost:/Data2/Work> cat ~/.local/share/flatpak/overrides/io.github.martinrotter.rssguard
[Context]
sockets=session-bus;
filesystems=host-etc;host-os;host;

[Session Bus Policy]
org.freedesktop.Flatpak=talk

rhack@localhost:/Data2/Work> which firefox
/usr/bin/firefox
rhack@localhost:/Data2/Work> firefox --version
Mozilla Firefox 125.0.3

And the screenshot:

![Screenshot_20240517_024517](https://github.com/martinrotter/rssguard/assets/44449170/8f81b539-01a3-4147-8cee-091d435e2d12)

And four screen shots showing the Flatseal settings for RSSGuard:

![Screenshot_20240517_024856](https://github.com/martinrotter/rssguard/assets/44449170/f23d43f4-0586-44f1-bd42-f3d154496cb3)

![Screenshot_20240517_025112](https://github.com/martinrotter/rssguard/assets/44449170/5ad79bca-6cba-4080-9062-8a70c4ac2d32)

![Screenshot_20240517_025130](https://github.com/martinrotter/rssguard/assets/44449170/2799e772-447b-4e35-b31d-9f9d53415268)

![Screenshot_20240517_025143](https://github.com/martinrotter/rssguard/assets/44449170/589b0800-d116-4b4d-827d-d1d7b698e469)

Hope this helps.

**Comment by richardstevenhack** [comment]
Here's the command output:

rhack@localhost:/Data2/Work> cat ~/.local/share/flatpak/overrides/global
[Context]
filesystems=home

OK, I just got up about an hour ago. I read the above request and ran RSSGuard from the command line with the --log option. When I clicked on the feed item and did a right-click, everything worked as it should. I was able to load the item to Firefox.  The problem was gone!

Then I quit RSSGuard and ran it from the KDE Task Manager pinned app as I usually do. The problem returned. I quit it again.

Then I ran it from the KDE menu directly and the problem persisted. 

So I wondered if some change in the KDE desktop which is out of sync with the installed flatpak might be causing the problem. So I uninstalled and reinstalled RSSGuard using the usual flatpak commands figuring it would regenerate the KDE desktop relationship.

Now running RSSGuard from the KDE menu, or the Task Manager pin, OR from the command line still shows the problem.

I don't know why it worked from the command line, but only one time. That is extremely weird.

As for the two message types requested, when the program operated correctly on first use I did see those messages when I was able to open one of the feed items in the browser. However, when the problem exists, those messages do NOT appear when I right-click on the feed item. I suspect this is because the entire option to use an external browser is greyed out and can not be clicked on. Since the problem has no returned no matter how the program is run, I can't show those messages. 

Right clicking on any feed item just generates messages of the type:
time="     5.085" type="debug" -> gui: Message list got focus with reason 'Qt::MouseFocusReason'.
time="     5.085" type="debug" -> gui: Current row changed - proxy 'QModelIndex(8,6,0x55e359dd7e30,MessagesProxyModel(0x55e359b364a0, name = MessagesProxyModel))', source 'QModelIndex(8,6,0x0,MessagesModel(0x55e359b7ef20))'.
time="    13.043" type="debug" -> gui: Message list got focus with reason 'Qt::PopupFocusReason'.

In case it might help, here is the config.ini file:
[config.ini.txt](https://github.com/martinrotter/rssguard/files/15355810/config.ini.txt)

**Comment by guihkx** [comment]
I used your config file here, and everything still works, so it's most likely not related to that...

>I suspect this is because the entire option to use an external browser is greyed out and can not be clicked on

I didn't even know the external browser menu option could get greyed out... LOL

But what happens when you just left-click on hyperlinks? That should launch the external web browser, too.

By the way, and this is very silly, but are you sure you don't have a duplicate installation of RSS Guard (e.g. through your distro's package manager)?

That's the only explanation I can think of for links not opening when you launch RSS Guard through KDE's apps menu... :man_shrugging: 

Can you record a quick video following these steps?

1. Run RSS Guard in the terminal: `flatpak run io.github.martinrotter.rssguard`
2. Open any article, from any feed
3. Left-click on the "URL" hyperlink under the WebView panel
4. Go back to the terminal window and see if we get any error or useful messages

Here's a video recording I did, following the steps above:

https://github.com/martinrotter/rssguard/assets/626206/7c9311db-e29c-4b12-bdbb-7e6580c1acf6

**Comment by richardstevenhack** [comment]
I don't know how to record a video on my system, but I followed the steps and that does work fine. Here is the log results:

[log.txt](https://github.com/martinrotter/rssguard/files/15358279/log.txt)

Left clicking on the URL in the Webview panel works and so does right-clicking on the URL which brings up the context menu for that action which allows opening in the external browser.

So it appears the only thing not working is why the right click on a feed article brings up the context menu with all the options except "Open with external tool" and "Labels" greyed out.

And I don't have a second installation of the program.

**Comment by guihkx** [comment]
>So it appears the only thing not working is why the right click on a feed article brings up the context menu with all the options except "Open with external tool" and "Labels" greyed out.

I'm almost sure that's because of a difference in behavior introduced by 4.7.0, actually related to this issue I reported earlier: #1410

If you want to confirm this, use the 4.6.6 AppImage and try to reproduce the issue with it.

Either way, that's a separate issue, unrelated to this one...

>I don't know how to record a video on my system

That's probably not necessary anymore, but you could use [GPU Screen Recorder](https://flathub.org/apps/com.dec05eba.gpu_screen_recorder) or [OBS Studio](https://flathub.org/apps/com.obsproject.Studio) next time.

Anyway, do you think the main issue has been resolved?

**Comment by richardstevenhack** [comment]
Now this is interesting. After doing the requested experiment, I decided to try running the program from the KDE menu again and testing. And guess what? The problem went away again! 

It seems like opening the feed item from the URL in Webview panel "jogged something loose", as it were. This implies some sort of "state change" is occurring.

I then ran it from the Task Manager pin - and the problem was back. I then ran it from the command line - and the problem remains. And I then ran it again from the KDE menu - and the problem remains.

I'm beginning to wonder if it has something to do with how I quit out of the program. I usually click the X close button in the upper right which closes it to the system tray. I almost never use the File menu quit option. I then may or may not right-click on the system tray icon and select quit. Perhaps some state is not being saved properly? I tried both ways and saved the logs from both attempts and ran a comparison but didn't see any difference from the point where the log shows the window being closed.

I tried to reproduce the working version a couple more times by running it from the KDE menu, clicking the URL in the Webview panel, then closing, then rerunning from the KDE menu and from the command line, and the problem persists. I can't seem to see any pattern in how it works once, then stops working.

I am trying to run the AppImage versions of the current version and the previous version, but at the moment it appears my AppImage setup isn't working. The AppImageLauncher I use appears to be broken and appimaged service isn't even installed. Probably another lousy Tumbleweed update broke something (as usual).

**Comment by richardstevenhack** [comment]
OK, got the AppImage straightened out.

Running the 4.7.0 AppImage, the problem persists.
Running the 4.6.6 AppImage, the problem goes away.

So I guess I'm stuck with 4.6.6 (at least until another Tumbleweed update breaks the AppImage - which I've had happen before.)

OR I can use the flatpak version and just forget about right-clicking on a feed item from now on.

**Comment by guihkx** [comment]
This is all very weird to me, and I'm out of ideas to debug this further, especially since I cannot reproduce this, at all...

>The AppImageLauncher I use appears to be broken and appimaged service isn't even installed. 

You can always just run the AppImage directly. Just give it execute permission and run by either double-clicking or via the command line.

**Comment by guihkx** [comment]
I'm not sure if you already answered this before, but anyway, when things are not working and you click on links, does nothing happen at all?

Does RSS Guard not even display an error in the GUI, or something like that?

**Comment by richardstevenhack** [comment]
I just solved the problem!

What I used to do was click on a feed, which displays the articles. Then I would scan down the articles and right-click on one that I wanted to open in the external browser. The context menu comes up, then I click on open with external browser.

I never clicked on the feed article BEFORE right-clicking on it.

However, now if I DO click on the feed article, then when I right-click the context menu opens as it should. If I just right-click on the article without first selecting it, the context menu comes up greyed out. So apparently the right-click selects the feed article AFTER it pops up the context menu. Since the context menu is being opened on a un-selected article it shows no options for that article.

If I select the article FIRST, then right-click the context menu opens and shows the options for the feed article.

I could swear I've never explicitly selected the article before, I just right-clicked it and everything worked.

Anyway, the problem is solved. All I have to do is select the article first, then right-click.

**Comment by guihkx** [comment]
Ahh, I understand now.

So the actual issue was RSS Guard greying out the "open in external browser" context menu option because you didn't select the article first using left-click. So it's not actually related to Flatpak at all...

Like I said earlier, to me this issue is closely related to #1410, which is technically a regression in behavior from 4.6.6, but we'll see how Martin will deal with it.

I suppose this can be closed now?

**Comment by richardstevenhack** [comment]
I hadn't looked at 1410 until you mentioned it again. I just looked at it, and yeah, pretty much the same issue. You have to select the article first, or none of the context menu options are available (except two - and their options are greyed out as well.)

It doesn't seem logical to me how it works. When you right-click on an object, it would seem to me to be obvious that one is selecting that object and therefore it should bring up the context menu with all options related to that object. I don't see why one would do the opposite.

Looking at the discussion in 1410, I can see where right-clicking on an article wouldn't necessarily bring up the Web panel view of the article. And right-clicking with CTRL for multiple selection is a different action altogether than merely right-clicking on an article.

But clearly right-clicking on an article implies both selecting the article and bringing up the context menu - otherwise why bother clicking on it?  LOL  Or at least it definitely implies at least bringing up the context menu.

[DawEdhel](https://github.com/DawEdhel) did comment in 1410 that  they prefer to right-click a single article in order to examine the details and keep it unread at the same time, which does make sense. Perhaps selecting an article shouldn't mean it's actually been read?

Actually I just played a bit more.  It appears that if you click on a feed, then RIGHT-click on a feed article, the feed article is highlighted in blue, indicating it has been selected, and the context menu does not appear. BUT if you click on another feed, then LEFT-click on an article, the feed article is highlighted, and then the context menu works. BUT then subsequently the context menu works for ALL the feed articles for that feed WITHOUT left-clicking first!

Clearly this is inconsistent behavior.

I think Martin needs to rethink the combination of actions that are possible and their sequence of execution. As I suggest, a right-click should at the very least select the item and bring up the context menu in that order. Just my two cents.

As far as I'm concerned, as long as I know how to make it work, it's no longer an issue for me.

**Comment by martinrotter** [comment]
#1410 was fixed to old behavior, which suited many people.

Can we therefore close?
