### ISSUE TITLE
[BUG]: stuck on first run with FreshRSS (SilentNetworkAccessManager)

### ISSUE THREAD

**Issue by dumprop** [martinrotter/rssguard#413]
#### Brief description of the issue.
It cannot get information from FreshRSS on first run 

#### How to reproduce the bug?
1. Install rssguard
2. Add FreshRSS account 
3. See that infinite loop

#### What was the expected result?
I see information from feed

#### What actually happened?
Infinite loop ("Settings of BaseNetworkAccessManager loaded")

#### Other information
close -> run it again = fix

* OS: macos
* RSS Guard version: 3.9.2

Log: https://pastebin.com/6TX69P2d

Also, once I caught a crash: https://pastebin.com/3EGKt4V2 (probably pressed too many buttons or restarted app)

**Comment by martinrotter** [comment]
OK, will investigate.

**Comment by martinrotter** [comment]
@dumprop How many feeds do you have added to your FreshRSS instance?

**Comment by martinrotter** [comment]
OK, there is no bug, problem is that the synchronization of feeds (!) (not of messages) is done when the account is added into RSS Guard. As part of the process, real icons of feeds are downloaded which is currently very slow because of bug in FreshRSS:

https://github.com/FreshRSS/FreshRSS/issues/3633
https://github.com/FreshRSS/FreshRSS/issues/3628

I temporarily work-arounded the problem and pushed new code. Please test after 15 minutes latest development build. I tested right now in Mac OS X from VirtualBox and it is now fixed.

**Comment by dumprop** [comment]
> @dumprop How many feeds do you have added to your FreshRSS instance?
> 
> Also, and this is important, did you test LATEST DEVELOPMENT build located at https://github.com/martinrotter/rssguard/releases/tag/devbuild ?

500-1500 feeds
Currently, it seems stable, but updating feeds still not pretty fast

**Comment by martinrotter** [comment]
> but updating feeds still not pretty fast

Updating feeds or updating messages?

**Comment by dumprop** [comment]
> > but updating feeds still not pretty fast
> 
> Updating feeds or updating messages?

updating messages, updating feeds its more one-time operation, so there no difference
Vienna very fast on 750 feeds
NNW too looks fast, but a bit slower
RSS guard up to 10x slower :(

**Comment by martinrotter** [comment]
> 
> 
> > > but updating feeds still not pretty fast
> > 
> > 
> > Updating feeds or updating messages?
> 
> updating messages, updating feeds its more one-time operation, so there no difference
> Vienna very fast on 750 feeds
> NNW too looks fast, but a bit slower
> RSS guard up to 10x slower :(

Yes, it is reported https://github.com/martinrotter/rssguard/issues/339 and I plan to address the issue very very soon.

You can at this point mitigate the problem by checking "Download unread messages only" and limiting the number of downloaded messages, let me know if those two options work well for you. They might be well enough for you, but that depends on how you use ToR/rssguard.
