### ISSUE TITLE
[FR]: Image support for NoWebEngine

### ISSUE THREAD

**Issue by Owyn** [martinrotter/rssguard#583]
### Brief description of the feature request

I'm fully content with the NoWebEngine version, but the only improvement I would like would be:

= Image support

I hope it won't be hard to implement, all it is needed is:

- the ability to display an image
- max-width \ max-height for images so no scrollbars appear and it fits into the viewer window

example feed with images: https://nitter.42l.fr/chgallery_/media/rss

**Comment by martinrotter** [comment]
There already was ticket https://github.com/martinrotter/rssguard/issues/205

I guess I can revisit this.

Would it work for you if there was a popup dialog showing the actual picture when you click the link in article?

**Comment by Owyn** [comment]
> popup 

that would be no different than simply clicking the image link to open it in browser, what's important for me is a preview so I would know whether it's worth clicking the image link or not

(there can be a setting to display images or not in the noengine)

**Comment by martinrotter** [comment]
so you would like to see images instantly?

or perhaps would button "Reload article with pictures" (that would download all pictures and re-display article) work for you?

**Comment by Owyn** [comment]
> so you would like to see images instantly?

yes

**Comment by martinrotter** [comment]
Fixed and will be polished.

**Comment by Owyn** [comment]
Images don't seem to be showing at all:
![image](https://user-images.githubusercontent.com/1309656/162576261-6b42d8a9-4b05-4998-a54e-800127e235b8.png)

```
<item>
      <title>Beyond the mouse: How the click became the soundtrack of our lives  @GreaterBombay https://www.hindustantimes.com/lifestyle/art-culture/beyond-the-mouse-how-the-click-became-the-soundtrack-of-our-lives-101649510764266.html</title>
      <dc:creator>@HindustanTimes</dc:creator>
      <description><![CDATA[<p>Beyond the mouse: How the click became the soundtrack of our lives  <a href="https://nitter.net/GreaterBombay" title="Rachel Lopez">@GreaterBombay</a> <a href="https://www.hindustantimes.com/lifestyle/art-culture/beyond-the-mouse-how-the-click-became-the-soundtrack-of-our-lives-101649510764266.html">hindustantimes.com/lifestyle…</a></p>
<img src="https://nitter.net/pic/card_img%2F1512784137542905862%2FUxvQ_26q%3Fformat%3Djpg%26name%3D800x320_1" style="max-width:250px;" />]]></description>
      <pubDate>Sat, 09 Apr 2022 13:26:58 GMT</pubDate>
      <guid>https://nitter.net/HindustanTimes/status/1512784134778892288#m</guid>
      <link>https://nitter.net/HindustanTimes/status/1512784134778892288#m</link>
    </item>
```
example feed with images: https://nitter.net/HindustanTimes/rss

**Comment by martinrotter** [comment]
that is nonwebengine? if so, right click the article inside preview window, hit "Reload with images"

feedback welcomed

**Comment by Owyn** [comment]
![image](https://user-images.githubusercontent.com/1309656/162578070-5998ca12-6930-46fe-8422-787e927ddc24.png)

It works after you click that, but doesn't work if you don't click that

and the setting doesn't seem to change anything:
![image](https://user-images.githubusercontent.com/1309656/162578108-d2d5a9f6-3fcd-44dd-9f64-07b9acf2ccd2.png)

also right-clicking the image doesn't seem to work, click goes thru it - so I can't open image with browser or save it as or drag it to the desktop to save it
![image](https://user-images.githubusercontent.com/1309656/162578137-088b213c-8185-473f-865e-c334592fe48a.png)

**Comment by Owyn** [comment]
also would be nice to hide "written by" because I have column "author" disabled in my feeds, yet it still shows it here and takes space

and to hide date too (cuz it's already shown in the feed list)

just show the title ad the url like it was before in the nowebengine, I just wanted to see images and not all the new stuff...

btw, here it looks weird,
- big space before the image
- webp images are broken (shown plain white)
![image](https://user-images.githubusercontent.com/1309656/162578519-8ded0c21-e86b-4df5-b9fa-2ff14a3e6433.png)
![image](https://user-images.githubusercontent.com/1309656/162578525-f729503a-9e00-42a4-89db-217f73a07a80.png)

here's how the same item looks in stable version: (looks very nice):

![image](https://user-images.githubusercontent.com/1309656/162578543-8c3ad9b9-a538-4fa0-86b5-9979e292e540.png)

**Comment by martinrotter** [comment]
context menu -> 

![image](https://user-images.githubusercontent.com/1255302/162583516-18c192d2-ac95-44e0-8536-d072e158e331.png)

**Comment by Owyn** [comment]
I tried clicking that as well but it didn't seem to affect anything

**Comment by martinrotter** [comment]
re-select message

**Comment by martinrotter** [comment]
anyway, this view mode is very WIP

i will probably re-add the old nwe as option

**Comment by Owyn** [comment]
old nwe + simply showing images would be perfect tbh

**Comment by martinrotter** [comment]
> old nwe + simply showing images would be perfect tbh

You are probably right. I will re-add new and offer all 3 options:

- webengine (default on webengine build)
- nwe (default on nwe build + webengine not built like it was so far)
- litehtml (highly WiP, will be available on both builds)

**Comment by martinrotter** [comment]
Done, added old nonwebengine, and supports images now.

**Comment by martinrotter** [comment]
Just pushed cec08b4eb. Context menu has "enable" switch for the feature. Highly experimental. Feedback welcomed.

![rssguard_hpX3b2XBaO](https://user-images.githubusercontent.com/1255302/165281998-992a77c2-bd94-4f12-8492-6cd1ce741c66.gif)

**Comment by Owyn** [comment]
Nice, though some kind of preloading would be welcomed - e.g. for unread articles

**Comment by martinrotter** [comment]
> Nice, though some kind of preloading would be welcomed - e.g. for unread articles

I think about it, at this point I do not clear the "cache" so once image is downloaded it just stays there. I think about regularly clearing the cache each 10-15 minutes maybe?

I just want the feature to be bug-free. Then we can talk about preloading, but preloading itself would not be that easy to implement.

**Comment by Owyn** [comment]
> regularly clearing the cache each 10-15 minutes maybe? 

That's way too frequent. Maybe once in two weeks? (and only for things which weren't accessed recently)

or at least - session-cache - you start the app - cache starts along with it - you close the app - cache is gone

**Comment by martinrotter** [comment]
> or at least - session-cache - you start the app - cache starts along with it - you close the app - cache is gone

That is what is there de-facto now.

**Comment by Owyn** [comment]
That's nice, 
if it had preloading so images would be instantly shown when opening a feed - it'd be perfect, 
but now with little wait time for when it loads - it's ok too

**Comment by martinrotter** [comment]
> That's nice, if it had preloading so images would be instantly shown when opening a feed - it'd be perfect, but now with little wait time for when it loads - it's ok too

The feature works like this now:
1. Some article/html is "set" into the viewer.
2. The viewer discovers what images are there.
3. Images are downloaded asynchronously.
4. Article/html is reset with images.

Thing is that there is some artificial "waiting" in 2 step. The viewer is waiting for some time to make sure it discovered all images/resources and at this point, "waiting" is 300 miliseconds. I could lower the value to for example 150 ms and it would require some testing to see if the value works OK and some images (particularly in BIG html/articles) are not skipped.

**Comment by Owyn** [comment]
Why is there waiting tho? Can't it look fir images lazily too?

But yea, that's what I have noticed - there's about a half second loading time for all images - I just thought it's the internet

**Comment by martinrotter** [comment]
Yes, it is rather technical. I will try to tweak behavior a bit to eliminate all excessive waiting.

**Comment by martinrotter** [comment]
@Owyn OK, I upgraded the feature and removed almost all unnecessary delays. Also now the "placeholder" image is now RED if the image cannot be loaded.

Can you test?

**Comment by Owyn** [comment]
Now some images load much faster I think,

but some images which worked before started errorring right away
[image] https://reaperscans.com/wp-content/uploads/2021/07/rr-175x238.png
![image](https://user-images.githubusercontent.com/1309656/165732407-32b759e1-3e4b-4f5d-950b-c68b59e82964.png)



[image] https://reaperscans.com/wp-content/uploads/2021/10/Return-to-Player-175x238.jpg
![image](https://user-images.githubusercontent.com/1309656/165732490-e7fa7307-9551-412e-af22-6fed6983b8e9.png)

**Comment by martinrotter** [comment]
i see, can you share URL/script of that feed?

**Comment by martinrotter** [comment]
Some images here also return red error placeholder.

![image](https://user-images.githubusercontent.com/1255302/165734318-ef2ad837-8966-4e53-a3ca-86b94ddccb23.png)


When clicked

![image](https://user-images.githubusercontent.com/1255302/165734341-cab5c064-0f22-4b46-b8ca-69d1e8212276.png)


When I try these in real web browser, I also get error.

**Comment by Owyn** [comment]
Both images showed fine in my browser when I clicked links in rssguard right away after rssguard shower errors, now they show "forbidden" yea, maybe cuz of the referrer (or other such mechanism)?

**Comment by Owyn** [comment]
Maybe site related and they just changed some urls real quick,
cuz feeds of other sites with images all showed fine now when I tested,
I'll see again in the future if the problem persists with that one

**Comment by martinrotter** [comment]
Basically all delay you see now should be network things - downloading of the image.

**Comment by Owyn** [comment]
also I've noticed multiple times that status bar text url of images get stuck sometimes
![image](https://user-images.githubusercontent.com/1309656/166119034-3d2f795b-3dd6-40ed-9518-74e56b807ded.png)

to reproduce
1. hover over an image
2. press enter to open the feed url
- it's now stuck

**Comment by Owyn** [comment]
and for some reason some images (reddit in particular) just aren't loading (not starting loading - so there isn't an error either) (but clicking the link shows them fine in browser)
![image](https://user-images.githubusercontent.com/1309656/166436937-fe7dc321-bda6-4c83-b6d3-494e7978c174.png)

feed url: `https://www.reddit.com/user/orange2946/.rss`
